angular.module('hq.constants', [])
    .factory('countries', function(gettextCatalog) {
        return {
            'AF': gettextCatalog.getString('Afghanistan'),
            'AX': gettextCatalog.getString('Åland Islands'),
            'AL': gettextCatalog.getString('Albania'),
            'DZ': gettextCatalog.getString('Algeria'),
            'AS': gettextCatalog.getString('American Samoa'),
            'AD': gettextCatalog.getString('Andorra'),
            'AO': gettextCatalog.getString('Angola'),
            'AI': gettextCatalog.getString('Anguilla'),
            'AQ': gettextCatalog.getString('Antarctica'),
            'AG': gettextCatalog.getString('Antigua and Barbuda'),
            'AR': gettextCatalog.getString('Argentina'),
            'AM': gettextCatalog.getString('Armenia'),
            'AW': gettextCatalog.getString('Aruba'),
            'AU': gettextCatalog.getString('Australia'),
            'AT': gettextCatalog.getString('Austria'),
            'AZ': gettextCatalog.getString('Azerbaijan'),
            'BS': gettextCatalog.getString('Bahamas'),
            'BH': gettextCatalog.getString('Bahrain'),
            'BD': gettextCatalog.getString('Bangladesh'),
            'BB': gettextCatalog.getString('Barbados'),
            'BY': gettextCatalog.getString('Belarus'),
            'BE': gettextCatalog.getString('Belgium'),
            'BZ': gettextCatalog.getString('Belize'),
            'BJ': gettextCatalog.getString('Benin'),
            'BM': gettextCatalog.getString('Bermuda'),
            'BT': gettextCatalog.getString('Bhutan'),
            'BO': gettextCatalog.getString('Bolivia, Plurinational State of'),
            'BQ': gettextCatalog.getString('Bonaire, Sint Eustatius and Saba'),
            'BA': gettextCatalog.getString('Bosnia and Herzegovina'),
            'BW': gettextCatalog.getString('Botswana'),
            'BV': gettextCatalog.getString('Bouvet Island'),
            'BR': gettextCatalog.getString('Brazil'),
            'IO': gettextCatalog.getString('British Indian Ocean Territory'),
            'BN': gettextCatalog.getString('Brunei Darussalam'),
            'BG': gettextCatalog.getString('Bulgaria'),
            'BF': gettextCatalog.getString('Burkina Faso'),
            'BI': gettextCatalog.getString('Burundi'),
            'KH': gettextCatalog.getString('Cambodia'),
            'CM': gettextCatalog.getString('Cameroon'),
            'CA': gettextCatalog.getString('Canada'),
            'CV': gettextCatalog.getString('Cape Verde'),
            'KY': gettextCatalog.getString('Cayman Islands'),
            'CF': gettextCatalog.getString('Central African Republic'),
            'TD': gettextCatalog.getString('Chad'),
            'CL': gettextCatalog.getString('Chile'),
            'CN': gettextCatalog.getString('China'),
            'CX': gettextCatalog.getString('Christmas Island'),
            'CC': gettextCatalog.getString('Cocos (Keeling) Islands'),
            'CO': gettextCatalog.getString('Colombia'),
            'KM': gettextCatalog.getString('Comoros'),
            'CG': gettextCatalog.getString('Congo'),
            'CD': gettextCatalog.getString('Congo, the Democratic Republic of the'),
            'CK': gettextCatalog.getString('Cook Islands'),
            'CR': gettextCatalog.getString('Costa Rica'),
            'CI': gettextCatalog.getString('Côte d\'Ivoire'),
            'HR': gettextCatalog.getString('Croatia'),
            'CU': gettextCatalog.getString('Cuba'),
            'CW': gettextCatalog.getString('Curaçao'),
            'CY': gettextCatalog.getString('Cyprus'),
            'CZ': gettextCatalog.getString('Czech Republic'),
            'DK': gettextCatalog.getString('Denmark'),
            'DJ': gettextCatalog.getString('Djibouti'),
            'DM': gettextCatalog.getString('Dominica'),
            'DO': gettextCatalog.getString('Dominican Republic'),
            'EC': gettextCatalog.getString('Ecuador'),
            'EG': gettextCatalog.getString('Egypt'),
            'SV': gettextCatalog.getString('El Salvador'),
            'GQ': gettextCatalog.getString('Equatorial Guinea'),
            'ER': gettextCatalog.getString('Eritrea'),
            'EE': gettextCatalog.getString('Estonia'),
            'ET': gettextCatalog.getString('Ethiopia'),
            'FK': gettextCatalog.getString('Falkland Islands (Malvinas)'),
            'FO': gettextCatalog.getString('Faroe Islands'),
            'FJ': gettextCatalog.getString('Fiji'),
            'FI': gettextCatalog.getString('Finland'),
            'FR': gettextCatalog.getString('France'),
            'GF': gettextCatalog.getString('French Guiana'),
            'PF': gettextCatalog.getString('French Polynesia'),
            'TF': gettextCatalog.getString('French Southern Territories'),
            'GA': gettextCatalog.getString('Gabon'),
            'GM': gettextCatalog.getString('Gambia'),
            'GE': gettextCatalog.getString('Georgia'),
            'DE': gettextCatalog.getString('Germany'),
            'GH': gettextCatalog.getString('Ghana'),
            'GI': gettextCatalog.getString('Gibraltar'),
            'GR': gettextCatalog.getString('Greece'),
            'GL': gettextCatalog.getString('Greenland'),
            'GD': gettextCatalog.getString('Grenada'),
            'GP': gettextCatalog.getString('Guadeloupe'),
            'GU': gettextCatalog.getString('Guam'),
            'GT': gettextCatalog.getString('Guatemala'),
            'GG': gettextCatalog.getString('Guernsey'),
            'GN': gettextCatalog.getString('Guinea'),
            'GW': gettextCatalog.getString('Guinea-Bissau'),
            'GY': gettextCatalog.getString('Guyana'),
            'HT': gettextCatalog.getString('Haiti'),
            'HM': gettextCatalog.getString('Heard Island and McDonald Islands'),
            'VA': gettextCatalog.getString('Holy See (Vatican City State)'),
            'HN': gettextCatalog.getString('Honduras'),
            'HK': gettextCatalog.getString('Hong Kong'),
            'HU': gettextCatalog.getString('Hungary'),
            'IS': gettextCatalog.getString('Iceland'),
            'IN': gettextCatalog.getString('India'),
            'ID': gettextCatalog.getString('Indonesia'),
            'IR': gettextCatalog.getString('Iran, Islamic Republic of'),
            'IQ': gettextCatalog.getString('Iraq'),
            'IE': gettextCatalog.getString('Ireland'),
            'IM': gettextCatalog.getString('Isle of Man'),
            'IL': gettextCatalog.getString('Israel'),
            'IT': gettextCatalog.getString('Italy'),
            'JM': gettextCatalog.getString('Jamaica'),
            'JP': gettextCatalog.getString('Japan'),
            'JE': gettextCatalog.getString('Jersey'),
            'JO': gettextCatalog.getString('Jordan'),
            'KZ': gettextCatalog.getString('Kazakhstan'),
            'KE': gettextCatalog.getString('Kenya'),
            'KI': gettextCatalog.getString('Kiribati'),
            'KP': gettextCatalog.getString('Korea, Democratic People\'s Republic of'),
            'KR': gettextCatalog.getString('Korea, Republic of'),
            'KW': gettextCatalog.getString('Kuwait'),
            'KG': gettextCatalog.getString('Kyrgyzstan'),
            'LA': gettextCatalog.getString('Lao People\'s Democratic Republic'),
            'LV': gettextCatalog.getString('Latvia'),
            'LB': gettextCatalog.getString('Lebanon'),
            'LS': gettextCatalog.getString('Lesotho'),
            'LR': gettextCatalog.getString('Liberia'),
            'LY': gettextCatalog.getString('Libya'),
            'LI': gettextCatalog.getString('Liechtenstein'),
            'LT': gettextCatalog.getString('Lithuania'),
            'LU': gettextCatalog.getString('Luxembourg'),
            'MO': gettextCatalog.getString('Macao'),
            'MK': gettextCatalog.getString('Macedonia, the Former Yugoslav Republic of'),
            'MG': gettextCatalog.getString('Madagascar'),
            'MW': gettextCatalog.getString('Malawi'),
            'MY': gettextCatalog.getString('Malaysia'),
            'MV': gettextCatalog.getString('Maldives'),
            'ML': gettextCatalog.getString('Mali'),
            'MT': gettextCatalog.getString('Malta'),
            'MH': gettextCatalog.getString('Marshall Islands'),
            'MQ': gettextCatalog.getString('Martinique'),
            'MR': gettextCatalog.getString('Mauritania'),
            'MU': gettextCatalog.getString('Mauritius'),
            'YT': gettextCatalog.getString('Mayotte'),
            'MX': gettextCatalog.getString('Mexico'),
            'FM': gettextCatalog.getString('Micronesia, Federated States of'),
            'MD': gettextCatalog.getString('Moldova, Republic of'),
            'MC': gettextCatalog.getString('Monaco'),
            'MN': gettextCatalog.getString('Mongolia'),
            'ME': gettextCatalog.getString('Montenegro'),
            'MS': gettextCatalog.getString('Montserrat'),
            'MA': gettextCatalog.getString('Morocco'),
            'MZ': gettextCatalog.getString('Mozambique'),
            'MM': gettextCatalog.getString('Myanmar'),
            'NA': gettextCatalog.getString('Namibia'),
            'NR': gettextCatalog.getString('Nauru'),
            'NP': gettextCatalog.getString('Nepal'),
            'NL': gettextCatalog.getString('Netherlands'),
            'NC': gettextCatalog.getString('New Caledonia'),
            'NZ': gettextCatalog.getString('New Zealand'),
            'NI': gettextCatalog.getString('Nicaragua'),
            'NE': gettextCatalog.getString('Niger'),
            'NG': gettextCatalog.getString('Nigeria'),
            'NU': gettextCatalog.getString('Niue'),
            'NF': gettextCatalog.getString('Norfolk Island'),
            'MP': gettextCatalog.getString('Northern Mariana Islands'),
            'NO': gettextCatalog.getString('Norway'),
            'OM': gettextCatalog.getString('Oman'),
            'PK': gettextCatalog.getString('Pakistan'),
            'PW': gettextCatalog.getString('Palau'),
            'PS': gettextCatalog.getString('Palestine, State of'),
            'PA': gettextCatalog.getString('Panama'),
            'PG': gettextCatalog.getString('Papua New Guinea'),
            'PY': gettextCatalog.getString('Paraguay'),
            'PE': gettextCatalog.getString('Peru'),
            'PH': gettextCatalog.getString('Philippines'),
            'PN': gettextCatalog.getString('Pitcairn'),
            'PL': gettextCatalog.getString('Poland'),
            'PT': gettextCatalog.getString('Portugal'),
            'PR': gettextCatalog.getString('Puerto Rico'),
            'QA': gettextCatalog.getString('Qatar'),
            'RE': gettextCatalog.getString('Réunion'),
            'RO': gettextCatalog.getString('Romania'),
            'RU': gettextCatalog.getString('Russian Federation'),
            'RW': gettextCatalog.getString('Rwanda'),
            'BL': gettextCatalog.getString('Saint Barthélemy'),
            'SH': gettextCatalog.getString('Saint Helena, Ascension and Tristan da Cunha'),
            'KN': gettextCatalog.getString('Saint Kitts and Nevis'),
            'LC': gettextCatalog.getString('Saint Lucia'),
            'MF': gettextCatalog.getString('Saint Martin (French part)'),
            'PM': gettextCatalog.getString('Saint Pierre and Miquelon'),
            'VC': gettextCatalog.getString('Saint Vincent and the Grenadines'),
            'WS': gettextCatalog.getString('Samoa'),
            'SM': gettextCatalog.getString('San Marino'),
            'ST': gettextCatalog.getString('Sao Tome and Principe'),
            'SA': gettextCatalog.getString('Saudi Arabia'),
            'SN': gettextCatalog.getString('Senegal'),
            'RS': gettextCatalog.getString('Serbia'),
            'SC': gettextCatalog.getString('Seychelles'),
            'SL': gettextCatalog.getString('Sierra Leone'),
            'SG': gettextCatalog.getString('Singapore'),
            'SX': gettextCatalog.getString('Sint Maarten (Dutch part)'),
            'SK': gettextCatalog.getString('Slovakia'),
            'SI': gettextCatalog.getString('Slovenia'),
            'SB': gettextCatalog.getString('Solomon Islands'),
            'SO': gettextCatalog.getString('Somalia'),
            'ZA': gettextCatalog.getString('South Africa'),
            'GS': gettextCatalog.getString('South Georgia and the South Sandwich Islands'),
            'SS': gettextCatalog.getString('South Sudan'),
            'ES': gettextCatalog.getString('Spain'),
            'LK': gettextCatalog.getString('Sri Lanka'),
            'SD': gettextCatalog.getString('Sudan'),
            'SR': gettextCatalog.getString('Suriname'),
            'SJ': gettextCatalog.getString('Svalbard and Jan Mayen'),
            'SZ': gettextCatalog.getString('Swaziland'),
            'SE': gettextCatalog.getString('Sweden'),
            'CH': gettextCatalog.getString('Switzerland'),
            'SY': gettextCatalog.getString('Syrian Arab Republic'),
            'TW': gettextCatalog.getString('Taiwan, Province of China'),
            'TJ': gettextCatalog.getString('Tajikistan'),
            'TZ': gettextCatalog.getString('Tanzania, United Republic of'),
            'TH': gettextCatalog.getString('Thailand'),
            'TL': gettextCatalog.getString('Timor-Leste'),
            'TG': gettextCatalog.getString('Togo'),
            'TK': gettextCatalog.getString('Tokelau'),
            'TO': gettextCatalog.getString('Tonga'),
            'TT': gettextCatalog.getString('Trinidad and Tobago'),
            'TN': gettextCatalog.getString('Tunisia'),
            'TR': gettextCatalog.getString('Turkey'),
            'TM': gettextCatalog.getString('Turkmenistan'),
            'TC': gettextCatalog.getString('Turks and Caicos Islands'),
            'TV': gettextCatalog.getString('Tuvalu'),
            'UG': gettextCatalog.getString('Uganda'),
            'UA': gettextCatalog.getString('Ukraine'),
            'AE': gettextCatalog.getString('United Arab Emirates'),
            'GB': gettextCatalog.getString('United Kingdom'),
            'US': gettextCatalog.getString('United States'),
            'UM': gettextCatalog.getString('United States Minor Outlying Islands'),
            'UY': gettextCatalog.getString('Uruguay'),
            'UZ': gettextCatalog.getString('Uzbekistan'),
            'VU': gettextCatalog.getString('Vanuatu'),
            'VE': gettextCatalog.getString('Venezuela, Bolivarian Republic of'),
            'VN': gettextCatalog.getString('Viet Nam'),
            'VG': gettextCatalog.getString('Virgin Islands, British'),
            'VI': gettextCatalog.getString('Virgin Islands, U.S.'),
            'WF': gettextCatalog.getString('Wallis and Futuna'),
            'EH': gettextCatalog.getString('Western Sahara'),
            'YE': gettextCatalog.getString('Yemen'),
            'ZM': gettextCatalog.getString('Zambia'),
            'ZW': gettextCatalog.getString('Zimbabwe')
        };
    })

.factory('usStates', function(gettextCatalog) {
    return {
        'AL': gettextCatalog.getString('Alabama'),
        'AK': gettextCatalog.getString('Alaska'),
        'AZ': gettextCatalog.getString('Arizona'),
        'AR': gettextCatalog.getString('Arkansas'),
        'CA': gettextCatalog.getString('California'),
        'CO': gettextCatalog.getString('Colorado'),
        'CT': gettextCatalog.getString('Connecticut'),
        'DE': gettextCatalog.getString('Delaware'),
        'DC': gettextCatalog.getString('District Of Columbia'),
        'FL': gettextCatalog.getString('Florida'),
        'GA': gettextCatalog.getString('Georgia'),
        'HI': gettextCatalog.getString('Hawaii'),
        'ID': gettextCatalog.getString('Idaho'),
        'IL': gettextCatalog.getString('Illinois'),
        'IN': gettextCatalog.getString('Indiana'),
        'IA': gettextCatalog.getString('Iowa'),
        'KS': gettextCatalog.getString('Kansas'),
        'KY': gettextCatalog.getString('Kentucky'),
        'LA': gettextCatalog.getString('Louisiana'),
        'ME': gettextCatalog.getString('Maine'),
        'MD': gettextCatalog.getString('Maryland'),
        'MA': gettextCatalog.getString('Massachusetts'),
        'MI': gettextCatalog.getString('Michigan'),
        'MN': gettextCatalog.getString('Minnesota'),
        'MS': gettextCatalog.getString('Mississippi'),
        'MO': gettextCatalog.getString('Missouri'),
        'MT': gettextCatalog.getString('Montana'),
        'NE': gettextCatalog.getString('Nebraska'),
        'NV': gettextCatalog.getString('Nevada'),
        'NH': gettextCatalog.getString('New Hampshire'),
        'NJ': gettextCatalog.getString('New Jersey'),
        'NM': gettextCatalog.getString('New Mexico'),
        'NY': gettextCatalog.getString('New York'),
        'NC': gettextCatalog.getString('North Carolina'),
        'ND': gettextCatalog.getString('North Dakota'),
        'OH': gettextCatalog.getString('Ohio'),
        'OK': gettextCatalog.getString('Oklahoma'),
        'OR': gettextCatalog.getString('Oregon'),
        'PA': gettextCatalog.getString('Pennsylvania'),
        'RI': gettextCatalog.getString('Rhode Island'),
        'SC': gettextCatalog.getString('South Carolina'),
        'SD': gettextCatalog.getString('South Dakota'),
        'TN': gettextCatalog.getString('Tennessee'),
        'TX': gettextCatalog.getString('Texas'),
        'UT': gettextCatalog.getString('Utah'),
        'VT': gettextCatalog.getString('Vermont'),
        'VA': gettextCatalog.getString('Virginia'),
        'WA': gettextCatalog.getString('Washington'),
        'WV': gettextCatalog.getString('West Virginia'),
        'WI': gettextCatalog.getString('Wisconsin'),
        'WY': gettextCatalog.getString('Wyoming')
    };
})

.factory('currencySymbols', function() {
    return {
        'CAD': '$',
        'EUR': '€',
        'GBP': '£',
        'USD': '$',
    };
})

.factory('orderStates', function(gettextCatalog) {
    return {
        'on_hold': gettextCatalog.getString('On Hold'),
        'pending': gettextCatalog.getString('Pending'),
        'released_to_store': gettextCatalog.getString('Released to Store'),
        'warehouse': gettextCatalog.getString('Warehouse'),
        'in_progress': gettextCatalog.getString('In Progress'),
        'timeout': gettextCatalog.getString('Timeout'),
        'declined': gettextCatalog.getString('Declined'),
        'held_to_complete': gettextCatalog.getString('Held to Complete'),
        'backordered': gettextCatalog.getString('Backordered'),
        'mispick': gettextCatalog.getString('Mispick'),
        'picking': gettextCatalog.getString('Picking'),
        'mispack': gettextCatalog.getString('Mispack'),
        'packing': gettextCatalog.getString('Packing'),
        'ready': gettextCatalog.getString('Ready'),
        'shipped': gettextCatalog.getString('Shipped'),
        'delivered': gettextCatalog.getString('Delivered'),
        'picked_up': gettextCatalog.getString('Picked Up'),
        'invoiced': gettextCatalog.getString('Invoiced'),
        'returned': gettextCatalog.getString('Returned'),
        'pending_returned': gettextCatalog.getString('Pending returned'),
        'refunded': gettextCatalog.getString('Refunded'),
        'canceled': gettextCatalog.getString('Canceled'),
        'auto_cancelled': gettextCatalog.getString('Auto-canceled'),
        'clearing': gettextCatalog.getString('Clearing'),
        'waiting': gettextCatalog.getString('Waiting'),
        'review': gettextCatalog.getString('Review'),
        'labeling': gettextCatalog.getString('Labeling'),
    };
})

.constant('constants', {
    maps: {
        google: {
            initialZoom: 3,
            detailZoom: 17,
        },
        usCenter: {
            lat: 37.1886,
            lng: -99.7657,
        },
    },
    flashTimeout: 2000,
    defaultCurrency: 'USD'
});
