dist: trusty
sudo: required
language: node_js
node_js:
  - stable
cache:
  apt: true
  directories:
    - $HOME/.npm
    - $HOME/.bower
    - $HOME/.sonar/cache
    - node_modules
    - bower_components
before_install:
  - npm config set progress=false
after_success:
  - CI/run_sonar.sh
notifications:
  slack: newstoreinc:XNb8M8zS4jRVxiJDvQ1sdVAD
before_deploy:
  - npm run gulp production
deploy:
  provider: script
  script: ./tools/deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    - secure: C8S4TjZfD4oRr54Tsg5qg61c3/u9fYsJbv1uFacI5dtCX8Wduuq83l66WxMeLUKQQDHXvjHT9PN1E7KUBxsmnUelXvkyXDikqmi+KKCZWUeI39rMq5CU8lAusfCHKKQ/i7jAC/Rhqt1wFHtU7+gARLeDSaPk3XMPDzyErxG0nY/YdHyjBuIj7m+Q6v4x6nFWCmuWbCwjetYvmWCg09b1bZcDqBTQ8UIiY38q/C93Kd+kulz9rmxibrI9bhYF7x8fp3mlNBHyov7YonBQMCUPdcJ1OhU9603RB82/jk71q/QrL3vWHQbg1A6nHLkKMRYAbqo/afTbooQg+MoYODIus04PEbkvW+dJH6uV7Or44uCdIH9hcOMz0HpRFTSi9PWJ+hZhbtYdKGNnI2Swvm5Ahj0ZkBrZ5FA/AaBv/EusBewPPUNRD7dYtMRl7okoTJOjq9TiCCU5A9/ZVc/G7YJ8UamH5TdYed1D4VEBfyAhBpwSJfXB+uMgxHtaBjDrzPXjYgLmsgUaWKOwFNxj2wtU4VCmHTUTTfd/BFE90hxSBmFVbKjuHZEeEuv7dA6iue9DtGeCfUyDWf+IofDh5UDrVqo0Upx0PUaPNYBiQBvMou+F8roAfv5oQAOHZwzwKSJm7hX0Gmxk4d+Ni8HpxRKPxVqbdfuSXzgkKtOKER6gjyQ=
    - secure: 3id778NZsrjtt5PVu8uGItqRyROzqg/N/yJ17+UGG+eMfAEew6ZGH3F9ZRihyp9i9dE9yVKl++YjJp228dBv1qX4ACYqqA9GddaEXH8LccIQUW2bDdssMbSjIYFRGwPKB82dPXVjG3eILP3AWz9BlcMXpWn0f1FvpCDlOmyzfH7RXADggpBoOglJKF6k1PnicLPKBuCJb3O8hsw7HYPCwzSstd7Yn5tRjhr0lQ60wyO0/ijz9wG7kNuz6i80uAuqJF6TmP7F0b6jbq1L+5Wx51qfOnSHnbOmcip+PkFg1/wYZZ+CWvhGH9bfIrOOXhgsINMkLs9xnbV8G11GB3rgcUvIeEvji1QkYl8qv0LEu44jwart7TSZz51znneuWuK+Ztaxc4O2MpAsweVXp8WZfMXSoH3MyHxo6gApJqbuDJmCmeeszmxX5BYX28fYUXrVeYTvBiMOptchsQY7uLzHfSJG8/qglMr/xdTi4dxFPUoHV62vvcAasOGjnoBy3Jw5O1TPsub7bRgUssdfQFXqZU3Ca3w0uuOARr5oy/rY5Fx6pGNsNWc+6p+ZCnOAufEPYQqWdbzuIJOfiG2uSHChBlH0TQuro2lSdE+s/9DEP3tfF0wLin6tAUkEKQ/wLIkrgo4KhA5opi66v8VDTCG43E9t+eYPLAFt/lnDN3piXVM=
    - secure: h7xyOtwG9LuqWH7AHqrpH3ZQ7DPxt1wnUezaj0QB8L0kykBkRJrMgo2pCQgupoFmgMh7D8e6WcIbGPTTKxYEhPn+KO5V01e+G5IFu73UgTOy0p426IEYnAcZecyH+XkNi+6PZ5U8J7apMxpCEF7IV+sPeNa6CB8Ouv2qfUTwaqp5Bs/BzCBocSFZAmZzJ/EDHX5VbC/n954wcozLgPAri+caH375xBxagyawOUHaM8g+Fihysg2z4UXUXp4hJeFuacDyZJah21jpyPcvLeMpj9ktdaoGaHg6w4cN3Snc7LLU+cAFBJxeqnJxMukq4k7Ry3ohfsmbrioEZY00yHIBjr5BxY57zJviG6ELAkA92Q9FGgNZSMXsU8YdTERZKBgChNufTHuQDa0hCrENDZ95f4cgTzjRp7k6rhOgPQwpBZlS3xkWYiNYxBTyE1Us39iez0yuWYDvcW526dpWw9AaZfpEcY3M9+uim84qnVe1Ve5mI8P8KyQsypz0UaGE+aXxxtzWPOMjU8mYz4ud9zKWSWOtqoCsW4VF83rDGQJM+nQWFTqMOMpsTJI18qsdQycV2L1AZfrEJV2lSP0Oa99cnduN1fkAqNT+TVkL7XT6VWm7QhnsmiGZNZOW49BPhy3Qdzn5OnBpEorDExbqqnCODPMCzhJi4V9C46D71wNR14Q=
    - secure: MCeXoC87d6OC9bd9ysaw8vy9tmTO0jgt4IGzSwiqARZxn8XrRQ6u6/mhOH6JxJy6KoCy/ZxXV6ym9UYf7aePqvkmU0FSyHF6h0Ihk2MT+c6ZU1Y3gsVsEAKMlR5P7tLYmxQMMT7UDcH+1wn7wdOuPVp+XtBHNou3ZtDe0Bx1x7tYPMSLYCd+PzgBRCW1YD93L6aPmJ8PtNk/lFNN/QP3CYUgksRxxo0prr4g2cOyDzc2h6Ga4fpC1seWxFWCtMrKbGMqzyUVRXfYUz3vRXIbGtIyFrEXXTYXnhSJ4VzNt5Co3ZtAb689kYT14ZRv4tJoA5O42L6PJncwFY+j+997jKqPpMSRfmZS/0fQR5MWa7TR/2v4PUZAMGm8OsKConY224YMB39XaDvvwaFXaLgM8Ky5mzUpayCNqkv9y2HJGfPhAIaGoJy1MLzMtBj4QQeH0Td2ehYiNm+sVSbQnui70oGhD9u75JuaSuO+nhEZjOcuQj4D1SA7EQuBgKhbiyydJOHHhobCw3tqlBKCnnYng4dUub3FSYX3ontvR0x8purO817mQrMI7pl2w1ynQlDVyhzyQlN8BH87xQNdu8hVVwwKJ0hA+HSeSmPbNscLVziyKmxxc3z982bYhhKkIJXdJpLEVVY0Yqtotm9/jj9LJbocMDxatoIAQUIy27JFraU=
